###
@Server_HostAddress = http://localhost:5081
###

GET {{Server_HostAddress}}/grid
Accept: application/json

###

PUT {{Server_HostAddress}}/grid/7/3?state=true
Accept: application/json

###

POST {{Server_HostAddress}}/grid/update
Accept: application/json

###

POST {{Server_HostAddress}}/grid/clear
Accept: application/json